### PR TITLE
shouldResubscribe option

### PR DESCRIPTION
**Pull request by damonmaria**
## The problem

The main reason for this PR is I have a couple of cases where compose ends up in an infinite loop. It goes something like this:
1. On first call to my `onPropsChange` I start an async data fetch and fire `onData` which shows a contained component in one style
2. Later ,once data arrives, `onData` is fired again and the component changes look drastically
3. This seems to cause React to fire `componentWillReceiveProps` with the same prop values as before
4. react-komposer then calls my `onPropsChange`, and so we go back to step one
5. Repeat forever grinding that browser tab to a halt

See the [note in the React docs](https://facebook.github.io/react/docs/component-specs.html#updating-componentwillreceiveprops) of `componentWillRecieveProps` for an explanation that this being fired with the same props is expected.

At a higher level, sometimes (often) the lifecycle of the component has to be taken into account in `onPropsChange`. Many users will expect it to only fire once per component. 

Previously there was no way to detect that `onPropsChange` is being called with the same props and the expensive / async operation does not need to be repeated. 
## What this PR does
1. The current `!pure` and `!shallowEqual` check for the props is done in `componentWillRecieveProps` _before_ `onPropsChange` is fired, not just in `shouldComponentUpdate`. This will stop a lot of existing redundent calls to `onPropsChange` but might somehow cause a backwards incompatible change if current react-komposer users have impure `onProposChange` functions but are not setting `pure: false` (not very likely IMHO). 
2. The above check can be overriden with a custom function passed in the options as `shouldResubscribe`. This allows the user to check for a change in only the props that affect the `onPropsChange` function. This is useful, for example, when there are multiple layers of `compose` components and props coming down from outer components then don't need to fire `onProposChange` on unrelated inner components.
## Other implementation paths not taken

I thought about binding `this` to the component so cache check info could be kept on the component and checked by `onPropsChange` but that breaks the pure function principle that this package aims for. Same with having the same cache info in a variable outside the `onPropsChange` function (that also has bugs in certain scenarios if mutliple components are used). 

I also thought about passing the old props into `onPropsChange` but that function already has enough parameters and it didn't seem good separation of concerns. 
## Tests / docs

Plenty of tests and API doc added. 

Also added `env: "mocha"` to `.eslintrc` otherwise ESlint bawked on `beforeEach()`.

### CODE REVIEW

**Comment by damonmaria** [comment]
Just committed a further addition that allows you to pass a fixed value (treated as truthy) for `shouldResubscribe`, instead of a function.

**Comment by clayne11** [comment]
You pass in nextProps and context but you also need to pass `this.context` to the `shouldResubscribe` function, just like you do with `this.props`.

**Comment by damonmaria** [comment]
Agree about `mocha` in `.eslintrc`. Should have done that.

I thought about passing the old/current context into the function, but does `componentWillReceiveProps` get called when the context changes? Because if not then `this.context` and the `context` param will always be the same. That was my assumption.

**Comment by clayne11** [comment]
I'm pretty sure it gets called when `context` changes because otherwise `context` would never update.

**Comment by damonmaria** [comment]
I'll add an enzyme test and see

**Comment by damonmaria** [comment]
Now also allows checking of changes to context. Tests added and API doc updated.

**Comment by clayne11** [comment]
I think you should squash your commits and rebase off of `master` so that this is ready to get pulled in. Make it as easy as possible for @arunoda.

I can't wait for this to make it in, performance will be WAY better.

**Comment by damonmaria** [comment]
@clayne11 This is my first PR so still figuring my way through. Will give it a go today.

**Comment by clayne11** [comment]
Let me know if you get stuck and I can point you in the right direction.

**Comment by damonmaria** [comment]
@clayne11 I think the best way to learn is to muddle your way through. Each time I understand git a bit more and a bit less at the same time :) 

Squashed and rebased. Ready to merge.

**Comment by clayne11** [comment]
Looks good to me. Hopefully @arunoda will pull this in soon!

Fixes #4 & #2

**Comment by damonmaria** [comment]
Hey @arunoda, I think this PR will solve a few different issues. There's thorough testing. Any chance of a merge?

**Comment by clayne11** [comment]
I've been using it in production and it's definitely fantastic. Please merge.

**Comment by markoshust** [comment]
The ticket at https://github.com/mobxjs/mobx/issues/84#issuecomment-235652897 explains a good use-case for merging this in...

**Comment by clayne11** [comment]
We really need this merged @arunoda. I'm currently using @damonmaria 's fork in production because I absolutely need this functionality.

**Comment by clayne11** [comment]
Any movement on this @arunoda? This is a critical feature that we need to have pulled in.

**Comment by arunoda** [comment]
Yep. This is pretty needed.
I'm going to start fresh with the 2.x targeting this problem with a cleaner API.
Releasing pretty soon (This week)

**Comment by clayne11** [comment]
Can you please just merge this and release a minor version with it? It's a
critical feature and this PR has been sitting here for over a month.

**Comment by arunoda** [comment]
With v2, we've a similar API.
Check [this](https://github.com/arunoda/react-komposer#should-subscribe).

**Pull request closed without merging**
