### PR TITLE
Add test mode and composer stub registration

### PR DESCRIPTION
**Pull request by MasterAM**
This is meant for testing purposes and for presenting components in isolation (e.g, in [react-storybook](https://github.com/kadirahq/react-storybook)), when those components require container components.

This provides a method to override the composer for a given "dumb" component without changing existing API.

This is done by calling `createStubComposers()` with the "dumb" component as the first argument, followed by the desired composer(s) and turning on test mode via `setTestMode(true)`.

Any call to a composer returned by `composeAll` with this "dumb" component will result in the override composers being used, instead of the original ones.

Calling `createStubComposers` with the same component later on will replace the override composers for it and calling  `setTestMode(false)` will disable test mode.

Overriding the composers for a given component should happen before the composition is executed. It can happen after calling `composeAll`, but before the actual container component is generated (by calling the resulting function with the "dumb" component).

This PR addresses https://github.com/kadirahq/react-storybook/issues/45

A simple example is available in https://github.com/kadirahq/react-storybook/issues/45#issuecomment-206030133

### CODE REVIEW

**Comment by wormyy** [comment]
What is the status on this PR? Looks really useful, I am dealing with the problem it solves right now.

**Comment by MasterAM** [comment]
I also think that being able to test or display complex components in isolation is important.
Arunoda suggested to discuss this, but I guess he is pretty busy with other stuff.

@arunoda, any chance you can ask someone to review this PR if you don't have time to do so yourself?

**Comment by arunoda** [comment]
I implemented a brand new stubbing functionality. With that, I hope we could close this.
What do you think?
See: https://github.com/kadirahq/react-komposer#stubbing

**Comment by arunoda** [comment]
I hope we could close this.

**Pull request closed without merging**
